<script setup>
import { ref } from 'vue'
import { useHead, useSeoMeta } from '@unhead/vue'

const pageName = ref('Home')

useHead({
  title: () => `${pageName.value} - Vue Demo`,
  meta: [
    { name: 'description', content: () => `Demo of ${pageName.value}` }
  ],
})

useSeoMeta({
  ogTitle: () => pageName.value,
  ogDescription: 'Generated by useSeoMeta',
  twitterCard: 'summary',
})

const pages = ['Home', 'About', 'Docs', 'Blog']

function setPage(name) {
  pageName.value = name
  // useHead 的 reactive 函数会自动同步到 document.title
}
</script>

<template>
  <div class="card">
    <h2>unhead / useHead 演示</h2>
    <p class="hint">看浏览器标签页的标题，会随按钮实时变化。</p>

    <div class="row">
      <button
        v-for="p in pages"
        :key="p"
        :class="{ active: p === pageName }"
        @click="setPage(p)"
      >
        {{ p }}
      </button>
    </div>

    <div class="meta-preview">
      <div><span class="label">title</span><span class="val">{{ pageName }} - Vue Demo</span></div>
      <div><span class="label">og:title</span><span class="val">{{ pageName }}</span></div>
      <div><span class="label">description</span><span class="val">Demo of {{ pageName }}</span></div>
    </div>
  </div>
</template>

<style scoped>
.card { font-family: system-ui, sans-serif; padding: 12px; color: #213547; max-width: 460px; }
.card h2 { font-size: 1.05rem; margin: 0 0 6px; }
.hint { font-size: 0.82rem; color: #666; margin: 0 0 10px; }
.row { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 12px; }
button { padding: 5px 12px; border-radius: 6px; border: 1px solid #ccc; background: #fff; cursor: pointer; font-size: 0.85rem; }
button.active { background: #42b883; color: #fff; border-color: #42b883; }
.meta-preview { background: #f6f8fa; border-radius: 8px; padding: 10px; font-size: 0.82rem; }
.meta-preview > div { display: flex; gap: 8px; padding: 3px 0; }
.label { color: #888; min-width: 80px; }
.val { color: #213547; font-family: ui-monospace, monospace; }
</style>
